upgraded units aragorn namelessHorror  bird
markourm/lotr pull request #1
Opened 2017-09-20 21:14 UTC by lendavhollandlane

2017-09-21 20:45 UTC, lendavhollandlane commented
new graphics for High Elves unit
Terrain 1 changed rabbit, coal, silkworm, prime timber resource graphics
Terrain 3 changed some green gems to colour gems
Terrain7 changed resource graphics of rabbit and pheasant, fish, flowers and trees with a house, deer, seagulls.
Terrain 8 changed forest terrain graphics.

2017-09-22 18:52 UTC, markourm requested changes
Pheasant -> rabbit
replace spy bird

2017-09-22 19:11 UTC, lendavhollandlane commented
I have changed as requested and committed changes

2017-09-22 19:13 UTC, markourm approved these changes

2017-09-22 19:13 UTC, merged